output_dir: ~/experiments/

dataset:
  class: Hetionet
  path: ~/datasets/knowledge_graphs/

task:
  class: KnowledgeGraphCompletion
  model:
    class: CMPNN
    input_dim: 32
    hidden_dims: [32, 32, 32, 32]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes
    dependent: yes
    set_boundary: no
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no


optimizer:
  class: Adam
  lr: 2.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 32

train:
  num_epoch: 10
  batch_per_epoch: 2000


metric: mrr
fast_test: 1000